name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@^v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test # will run `yarn test` command
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@^v3.0.0
        with:
          cmd: install # will run `yarn install` command
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: https://npm.pkg.github.com/
      - run: yarn ci
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
